### ISSUE TITLE
Check Program Indicators on Adult Woman program

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#176]
For some strange reason the program indicator is 0.0 in Android when in the web is not 0.0

**Comment by idelcano** [comment]
continue in this branch: https://github.com/EyeSeeTea/dhis2-android-sdk/tree/feature-add_event_date_programrule

**Comment by tokland** [comment]
(cc @idelcano in case I am missing something)

Changes pushed to EyeSeeTea/dhis2-android-sdk/tree/feature-add_event_date_programrule.  Some comments before creating a PR. About the behaviour:

- If the program has no event date (the first event is used in the former code), then the expression evaluates to 0.0. Should this be changed? The web does not work very well neither, it shows negative values:

![Screenshot_20171102-122435.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1c3781777216455f17924d6b66af3006b1300051bff054a5556f9f08879a3e23579dc580ebb87385f77973540a5b8d41aea13a632c91edbe2e3d7158abd7f37ed998e48341f001880f95f37a99a43cf5dff59ac.png)

- When there is event date now it works, but note that the expression is always evaluated to a double, so it shows decimals:

![Screenshot_20171102-122448.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1c3781777216455f17924d1bb6af3006b1300051bff054a5556f9f08879a3e23579dc580ebb87385f77973540a5b8d41aea13a632c91edbe2e3d7158abd7f37ed998e48341f001880f95f36a09c4cc85ffe59ac.png)

About the code:

- I've removed the `alterinativeEvaluation` code. As far as I can see, there is no need to do anything here, d2 functions are already handled by `ExpressionFunctions.java` (https://github.com/EyeSeeTea/dhis2-android-sdk/blob/feature-add_event_date_programrule/core/src/main/java/org/hisp/dhis/android/sdk/utils/support/math/ExpressionFunctions.java). 
- I've added quotes to replaced values, since they may be also strings, not only numbers (as it happens with dates, for example).
- I have replaced`DateUtils.getMediumDate` by `DateUtils.parseDate`, the former only accepts dates in the format `YYYY-MM-DD` while the second accepts also strings formats that include the time (that's what we have here).

**Comment by idelcano** [comment]
@tokland 
> If the program has no event date (the first event is used in the former code), then the expression evaluates to 0.0. Should this be changed? The web does not work very well either, it shows negative values:

Sorry but i don't remember how works this program rule... 
The objective is make the app work like the web, but the initial numbers of the web looks more like UI bug... 

can you investigate that program rule? i think you will take the better decision about that.

> When there is event date now it works, but note that the expression is always evaluated to a double, so it shows decimals:

The web doesn't shown decimals values for that program rule, but maybe other similar program rules has decimals, i think we can trim the decimals in the UI after show the program rule result. what do you think?


The branch could have some bugs, feel free to change everything. 
And good job replacing alterinativeEvaluation function. It was a temp solution because i couldn't make it works with regexp.

**Comment by tokland** [comment]
Ok, I've created TextUtils.fromDouble to show numbers as the web app does, ex: 12,00 -> 12. 4,54 -> 5,54. If the evaluation of the expression fails -> empty string (instead of 0.0, which does not make sense)
