### ISSUE TITLE
Enrollment complete action is not being uploaded with the synchronization

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#95]

**Comment by xurxodev** [comment]
@ifoche It's a server problem, there are two cases where it does not do well:

1 - For Child program if already exists the enrollment in the server and complete it on Android and synchronizes does not do it well because it gives 500 error when trying to send a put request.
2 - if you complete in Android without it exists on the server and then synchronize, we send completed status but enrollment is created in the server as active, I suppose that the server post method always creates as active the enrollment.
3 - for another program than the child programme. I create the enrollment, upload it to the server and then complete in Android and synchronize then enrollment is updated to complete.
